using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace XmlDocGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class XmlDocSummaryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Pick up every AdditionalFile whose path ends in ".xml"
        //    (MSBuild forwards these via <AdditionalFiles Include="..." />).
        IncrementalValuesProvider<AdditionalText> docFiles = context
            .AdditionalTextsProvider
            .Where(f => f.Path.EndsWith(".xml", StringComparison.OrdinalIgnoreCase));

        // 2. Parse each into (id, summary) entries.
        IncrementalValuesProvider<DocEntry> entries = docFiles
            .SelectMany((file, ct) => ParseDocFile(file, ct))
            .Where(e => e is not null)!
            .Select((e, _) => e!);

        // 3. Collect and emit a single source file with the dictionary.
        context.RegisterSourceOutput(
            entries.Collect(),
            static (spc, all) => EmitSummaryProvider(spc, all));
    }

    private static IEnumerable<DocEntry> ParseDocFile(
        AdditionalText file, CancellationToken ct)
    {
        SourceText? text = file.GetText(ct);
        if (text is null) yield break;

        XDocument doc;
        try
        {
            doc = XDocument.Parse(text.ToString(), LoadOptions.None);
        }
        catch
        {
            yield break;
        }

        XElement? root = doc.Root;
        if (root is null) yield break;

        foreach (XElement member in root.Elements("members").Elements("member"))
        {
            ct.ThrowIfCancellationRequested();

            string? name = (string?)member.Attribute("name");
            if (name is null || name.Length < 2) continue;

            // The first two characters of a doc id are the kind prefix:
            //   T:  types
            //   F:  fields (e.g. AvaloniaProperty statics)
            //   P:  properties
            //   M:  methods
            //   E:  events
            string prefix = name.Substring(0, 2);
            if (prefix is not ("T:" or "F:" or "P:" or "M:" or "E:"))
            {
                continue;
            }

            XElement? summary = member.Element("summary");
            if (summary is null) continue;

            string cleaned = NormalizeWhitespace(summary.Value);
            if (string.IsNullOrWhiteSpace(cleaned)) continue;

            // We pass the FULL id (with prefix) to ShouldInclude so it can
            // strip the prefix itself, but we only need it to gate the
            // namespace. The stored key is the prefix-stripped form.
            if (!ShouldInclude(name)) continue;

            yield return new DocEntry(name.Substring(2), cleaned);
        }
    }

    private static bool ShouldInclude(string id)
    {
        // Strip the "T:" / "F:" / "P:" / "M:" / "E:" prefix; the rest is
        // the fully qualified declaration name.
        string name = id.Substring(2);

        return name.StartsWith("Avalonia.Controls", StringComparison.Ordinal)
            || name.StartsWith("Avalonia.Controls.Primitives", StringComparison.Ordinal)
            || name.StartsWith("Avalonia.Layout", StringComparison.Ordinal)
            || name.StartsWith("Avalonia.Media", StringComparison.Ordinal)
            || name.StartsWith("Avalonia.Input", StringComparison.Ordinal)
            || name.StartsWith("Avalonia.Visuals", StringComparison.Ordinal);
    }

    private static string NormalizeWhitespace(string text)
    {
        var sb = new StringBuilder(text.Length);
        bool prevSpace = false;
        foreach (char c in text)
        {
            if (char.IsWhiteSpace(c))
            {
                if (!prevSpace && sb.Length > 0) sb.Append(' ');
                prevSpace = true;
            }
            else
            {
                sb.Append(c);
                prevSpace = false;
            }
        }
        return sb.ToString().Trim();
    }

    private static void EmitSummaryProvider(
        SourceProductionContext spc,
        ImmutableArray<DocEntry> entries)
    {
        var unique = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (DocEntry e in entries)
        {
            // Last write wins for duplicates; Ordinal comparer keeps things stable.
            unique[e.Id] = e.Summary;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace ControlCatalog.Helper;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class XmlDocProvider");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<string, string> _summaries = new()");
        sb.AppendLine("    {");

        foreach (KeyValuePair<string, string> kv in unique.OrderBy(p => p.Key, StringComparer.Ordinal))
        {
            sb.Append("        { ");
            sb.Append(Escape(kv.Key));
            sb.Append(", ");
            sb.Append(Escape(kv.Value));
            sb.AppendLine(" },");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static string? GetSummary(string id)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _summaries.TryGetValue(id, out var s) ? s : null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("XmlDocProvider.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string Escape(string s)
    {
        return "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }

    private sealed class DocEntry
    {
        public string Id { get; }
        public string Summary { get; }

        public DocEntry(string id, string summary)
        {
            Id = id;
            Summary = summary;
        }
    }
}